### ISSUE TITLE
@ContextVariable lost in v1.3.1 

### ISSUE THREAD

**Issue by nderjung** [Nimrodda/WizarDroid#75] opened 2015-08-17 16:09 UTC
Simply, any context variable is not saved after updating to 1.3.1. However functionality resumes as expected in 1.3.0.

**Comment by Nimrodda** [comment] 2015-08-19 18:35
Have you tested it with the sample app?
I just ran the tests (`./gradle connectedCheck` from project root) and everything seems to be fine.
I could see that the text which was inserted in the first step showed up in the last step without any issue.
Could you please provide code snippet? I need more info what you're doing.

**Comment by Nimrodda** [comment] 2015-10-09 21:31
Any news on that? I need to know if you were able to reproduce it with the sample app or at least tell me how to reproduce or refer me to an example you made.

**Comment by Nimrodda** [comment] 2015-11-07 11:32
Closing as the OP haven't replied.

**Closed as completed by Nimrodda** 2015-11-07 11:32 UTC
