### ISSUE TITLE
WizardStep's onResume() method not working properly

### ISSUE THREAD

**Issue by Ajmera-Infotech** [Nimrodda/WizarDroid#66] opened 2015-05-20 07:35 UTC
When you host a view pager in a fragment you have to specify getChildFragmentManager() to its adapter. You have specified activity.getSupportFragmentManager().

You can read this for help : http://stackoverflow.com/questions/14740445/what-is-difference-between-getsupportfragmentmanager-and-getchildfragmentmanag

**Comment by Nimrodda** [comment] 2015-05-29 13:25
What is the actual bug you're experiencing? Please provide specific details.

**Comment by Ajmera-Infotech** [comment] 2015-07-13 07:38
I was trying to change labels of the wizard page in on resume method of the wizard steps. But onResume method did not call properly.

**Comment by Nimrodda** [comment] 2015-07-14 12:17
So is the issue now fixed?

**Comment by Ajmera-Infotech** [comment] 2015-07-14 13:09
No. It is not.

**Comment by Nimrodda** [comment] 2015-08-07 18:34
Can you paste your code here?

**Comment by Nimrodda** [comment] 2015-08-19 19:51
The issue is fixed in the upcoming release.

**Closed as completed by Nimrodda** 2015-08-19 19:51 UTC
